### ISSUE TITLE
Editing After forking: checklist of editing

### ISSUE THREAD

**Issue by CaitlinBate** [ocean-tracking-network/2023-01-ACT-advanced-workshop#1]
**gh-pages** --> create a new branch to make these changes. use `git checkout -b ＜new-branch＞`

- [x] - edit the code within each episode to remove the lines that apply to different Nodes (https://github.com/ocean-tracking-network/2023-01-ACT-advanced-workshop/pull/4)
- [x] - edit episode 00 code to remove any packages we will not be discussing
- [x] - remove entire lessons we're not teaching and re-number the episodes accordingly
- [x] - edit index.md to include an accurate summary of the workshop
- [x] - edit config.yml to have accurate title
- [x] - edit README.md
- [x] - remove excess files from Resources folder (https://github.com/ocean-tracking-network/2023-01-ACT-advanced-workshop/pull/5)
- [x] -  ~~remove excess files from Data folder~~
- [x] - ~~remove excess files from Code folder~~
- [x] - edit setup.md, including link to git repo (two places to change this) and remove extra packages we dont need
- [x] - ~~edit setup/setup.R, including link to git repo (two places to change this) and remove extra packages we dont need~~
- [x] - edit Resources/install_instructions.docx, including link to git repo (two places to change this) and remove extra packages we dont need

**master** --> create a new branch to make these changes. use `git checkout -b ＜new-branch＞`
- [x] - remove excess files from Data folder
- [x] - remove excess files from Code folder
- [x] - edit setup/setup.R, including link to git repo (two places to change this) and remove extra packages we dont need
- [x] - edit setup/install_instructions.docx, including link to git repo (two places to change this) and remove extra packages we dont need

**Comment by CaitlinBate** [comment]
first round of gh-pages edits https://github.com/ocean-tracking-network/2023-01-ACT-advanced-workshop/pull/2

**Comment by CaitlinBate** [comment]
master edits https://github.com/ocean-tracking-network/2023-01-ACT-advanced-workshop/pull/3

**Comment by CaitlinBate** [comment]
resources #5 and removing code from within lessons #4 done
